import { Reserva } from "@/types/types";
import { preloadTables } from "./preloadTables";

export const preloadReservation: Reserva[] = [
  {
    id: "1",
    fecha: "2023-09-15",
    hora: "20:00",
    personas: 4,
    precio: 100,
    deposito: 20,
    estado: "confirmada",
    mesa: preloadTables.find((table) => table.id === "1")!,
    notas: "Sin notas",
  },
  {
    id: "2",
    fecha: "2023-09-15",
    hora: "21:00",
    personas: 5,
    precio: 120,
    deposito: 30,
    estado: "confirmada",
    mesa: preloadTables.find((table) => table.id === "2")!,
    notas: "Sin notas",
  },
  {
    id: "3",
    fecha: "2023-09-15",
    hora: "22:00",
    personas: 5,
    precio: 150,
    deposito: 40,
    estado: "pendiente",
    mesa: preloadTables.find((table) => table.id === "3")!,
    notas: "Sin notas",
  },
  {
    id: "4",
    fecha: "2023-09-15",
    hora: "22:00",
    personas: 10,
    precio: 200,
    deposito: 50,
    estado: "confirmada",
    mesa: preloadTables.find((table) => table.id === "4")!,
    notas: "Sin notas",
  },
  {
    id: "5",
    fecha: "2023-09-15",
    hora: "23:00",
    personas: 2,
    precio: 80,
    deposito: 10,
    estado: "pendiente",
    mesa: preloadTables.find((table) => table.id === "5")!,
    notas: "Sin notas",
  },
  {
    id: "6",
    fecha: "2023-09-15",
    hora: "23:00",
    personas: 4,
    precio: 100,
    deposito: 20,
    estado: "confirmada",
    mesa: preloadTables.find((table) => table.id === "6")!,
    notas: "Sin notas",
  },
];
