import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/NavBar";
import Footer from "@/components/Footer";
import { AuthProvider } from "@/context/AuthContext";
import { ReservationProvider } from "@/context/ReservationContext";
import ChatbotButton from "@/components/chatbot/ChatBotButton"



const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "MonteVino",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} min-h-screen flex flex-col`}
      >
        <AuthProvider>
          <ReservationProvider>
          <Navbar />
          <main className="flex-1">{children}</main>
          <Footer />
          </ReservationProvider>
        </AuthProvider>
        <ChatbotButton />
      </body>
    </html>
  );
}
